<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
    <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.Resilience" Version="10.10.0" />
    <PackageReference Include="Microsoft.Kiota.Bundle" Version="2.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LibCurlImpersonate\LibCurlImpersonate.csproj" />
  </ItemGroup>
</Project>
